name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and tag Docker image
        run: |
          IMAGE_ID=ghcr.io/tawmu/nextdns-docker
          GIT_SHA=${{ steps.vars.outputs.sha_short }}
          
          docker build -t $IMAGE_ID:$GIT_SHA -t $IMAGE_ID:latest .

      - name: Push Docker images
        run: |
          IMAGE_ID=ghcr.io/tawmu/nextdns-docker
          GIT_SHA=${{ steps.vars.outputs.sha_short }}
          
          docker push $IMAGE_ID:$GIT_SHA
          docker push $IMAGE_ID:latest
